# Generated by Django 3.1.2 on 2020-10-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puffer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrafanaSnapshot',
        ),
        migrations.DeleteModel(
            name='Participate',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
