# Generated by Django 3.1.2 on 2020-10-22 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puffer', '0003_audiencefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(blank=True, default=0)),
                ('audio_file', models.FileField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f53725f3e20>/audio_<django.db.models.fields.FloatField>')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
