# Generated by Django 3.1.2 on 2020-10-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puffer', '0004_audiofeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofeedback',
            name='audio_file',
            field=models.FileField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f6eb495ae20>/audio_<django.db.models.fields.FloatField>'),
        ),
    ]
