# Generated by Django 3.1.2 on 2020-11-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puffer', '0006_auto_20201104_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
